name: "ESLint"

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Run lint script
        run: bun run lint